apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |
    CREATE TABLE todos (
      id INT PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      status BOOLEAN NOT NULL
    );

    INSERT INTO todos (id, title, status)
    VALUES (0, 'Buy groceries', FALSE);

    INSERT INTO todos (id, title, status)
    VALUES (1, 'Finish homework', FALSE);

    INSERT INTO todos (id, title, status)
    VALUES (2, 'Call mom', TRUE);

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: admin-poc
            - name: POSTGRES_PASSWORD
              value: poc-ssip
            - name: POSTGRES_DB
              value: todolist
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: postgres-init-scripts
          configMap:
            name: postgres-init-scripts

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP